### PR TITLE
make this plugin compatible with logstash 5.x

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Comment by guyboertje** [comment]
one small teeny thing.
Changelog reads `Update dependency to logstash-core-plugin-api > 1.60 < 2.0`
should this be `< 3.0`?

**Comment by jsvd** [comment]
fixed
build failing due to https://github.com/bundler/bundler/issues/5349

**Comment by guyboertje** [comment]
I feel, this
```ruby
            case field_type
            when 'datetime'
              event.set(event_key, LogStash::Timestamp.parse(value))
            when 'date'
              event.set(event_key, LogStash::Timestamp.parse(value))
            else
              event.set(event_key, value)
            end
```
should be
```ruby
            case field_type
            when 'datetime', 'date'
              event.set(event_key, LogStash::Timestamp.parse(value))
            else
              event.set(event_key, value)
            end
```
Your call.
It does not appear that the VCR fixtures would test the datetime or date case clause. Maybe verify that the specs do execute that path?

**Comment by guyboertje** [comment]
LGTM (whether you choose to change the case statement or not)

**Pull request closed without merging**
